name: PR Preview & Test Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate:
    name: Validate HTML & Links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install HTML validation tools
        run: |
          npm install -g html-validator html-validate html-proofer

      - name: Validate HTML files
        continue-on-error: true
        run: |
          echo "Validating HTML files..."
          find . -name "*.html" -not -path "./assets/vendor/*" -not -path "./node_modules/*" | while read file; do
            echo "Validating: $file"
            html-validator --file="$file" --verbose || true
          done

      - name: Check for broken links (basic check)
        continue-on-error: true
        run: |
          echo "Checking for common HTML issues..."
          grep -r "href=\"#" . --include="*.html" || echo "No anchor links found"

  build:
    name: Build & Prepare for Deployment
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare deployment package
        run: |
          echo "Building deployment package..."
          mkdir -p dist
          # Copy all necessary files for static site
          cp -r *.html dist/ 2>/dev/null || true
          cp -r assets dist/ 2>/dev/null || true
          cp -r blog dist/ 2>/dev/null || true
          cp -r forms dist/ 2>/dev/null || true
          cp -r checklists dist/ 2>/dev/null || true
          cp -r assets/docs dist/assets/ 2>/dev/null || true
          cp robots.txt dist/ 2>/dev/null || true
          cp sitemap.xml dist/ 2>/dev/null || true
          echo "Build complete!"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: website-build
          path: dist
          retention-days: 7

  deploy-preview:
    name: Deploy Preview
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request'
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: website-build
          path: dist

      - name: Deploy to GitHub Pages (Preview)
        uses: peaceiris/actions-gh-pages@v3
        if: github.event_name == 'pull_request'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: preview/pr-${{ github.event.pull_request.number }}
          # This creates a preview at: https://<username>.github.io/<repo>/preview/pr-<number>/
          # Note: You may need to configure GitHub Pages settings

      - name: Comment PR with preview link
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          script: |
            const previewUrl = `https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/preview/pr-${{ github.event.pull_request.number }}/`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `✅ **Test Deployment Complete!**\n\n📦 Preview URL: ${previewUrl}\n\n⚠️ Note: Preview may take a few minutes to be accessible.`
            });

